#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.garmin_email = "example@yunohost.org"
    args.garmin_password = "SuperDuper_StrongPassw0rd"
    args.fittrackee_id = "123456789"
    args.fittrackee_secret = "123456789bépoè"
    args.fittrackee_domain = "fittrackee@yunohost.org"


    test_upgrade_from.316feb1.name = "0.8.4"
    test_upgrade_from.356853c.name = "0.9.1"
